apiVersion: apps/v1
kind: Deployment
metadata:
    name: ecommerce-backend-deployment
    labels:
        app: ecommerce-backend
spec:
    # US-Standard: Mindestens 2 Instanzen parallel laufen lassen (Ausfallsicherheit)
    replicas: 2
    selector:
        matchLabels:
            app: ecommerce-backend
    template:
        metadata:
            labels:
                app: ecommerce-backend
        spec:
            serviceAccountName: ecommerce-backend
            containers:
                - name: ecommerce-backend-container
                  image: alexcell157/event-driven-spring-aws-showcase:latest
                  ports:
                      - containerPort: 8081
                  env:
                      - name: SPRING_PROFILES_ACTIVE
                        value: "prod"
                      - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
                        value: "kafka-service:9092"
                      - name: SPRING_KAFKA_CONSUMER_GROUP_ID
                        value: "ecommerce-showcase-group"
                      - name: SPRING_CLOUD_AWS_REGION_STATIC
                        value: "eu-central-1"
                      - name: CUSTOM_AWS_S3_BUCKET_NAME
                        value: "ecommerce-order-archive-showcase"
                      - name: CUSTOM_AWS_DYNAMODB_ANALYTICS_TABLE
                        value: "ECommerceAnalyticsDashboard"
                      - name: CUSTOM_AWS_DYNAMODB_PROCESSED_TABLE
                        value: "ProcessedOrders"
                      - name: CUSTOM_KAFKA_TOPIC_NAME
                        value: "orders-v1"
                  resources:
                      limits:
                          cpu: "500m"
                          memory: "512Mi"
                      requests:
                          cpu: "250m"
                          memory: "256Mi"

---
apiVersion: v1
kind: ServiceAccount
metadata:
    name: ecommerce-backend

---
apiVersion: v1
kind: Service
metadata:
    name: ecommerce-backend-service
spec:
    selector:
        app: ecommerce-backend
    ports:
        - protocol: TCP
          port: 8081      # Der Port, unter dem der Service im Cluster erreichbar ist
          targetPort: 8081 # Der Port im Container
    type: LoadBalancer  # Macht die API für externe curl-Anfragen im Internet zugänglich
